name: Metrics
on:
  schedule: 
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Basic metrics
          base: header, activity, repositories
          # Additional plugins
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_achievements: yes
